// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderProcess.Data;

#nullable disable

namespace OrderProcess.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240704085326_dltype")]
    partial class dltype
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderProcess.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryCode")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("groupno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("OrderProcess.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChainCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditLimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardLimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardTerm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Whseno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salesman")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OrderProcess.Core.Entities.DealCodes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("DealDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DealEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DealStart")
                        .HasColumnType("date");

                    b.Property<int>("Dealcode")
                        .HasColumnType("int");

                    b.Property<string>("DlTyoe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dealType")
                        .HasColumnType("int");

                    b.Property<int>("freegoods")
                        .HasColumnType("int");

                    b.Property<int>("minimumQty")
                        .HasColumnType("int");

                    b.Property<double>("rate")
                        .HasColumnType("float");

                    b.Property<int>("whseno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DealCodes");
                });

            modelBuilder.Entity("OrderProcess.Core.Entities.DealCustomerScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerScopeJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DealCode")
                        .HasColumnType("int");

                    b.Property<string>("DealDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DealCodeCustomerScope");
                });

            modelBuilder.Entity("OrderProcess.Core.Entities.DealProductScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DealCode")
                        .HasColumnType("int");

                    b.Property<string>("DealDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductScopeJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductScope");
                });

            modelBuilder.Entity("OrderProcess.Core.Entities.DealcodeMaster", b =>
                {
                    b.Property<string>("dldesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dltype")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<string>("typedesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("dealtype", (string)null);
                });

            modelBuilder.Entity("OrderProcess.Core.Entities.OrderEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("OrderCS")
                        .HasColumnType("float");

                    b.Property<string>("Packing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdNo")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("basePrice")
                        .HasColumnType("float");

                    b.Property<DateOnly>("poDate")
                        .HasColumnType("date");

                    b.Property<int>("poNo")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderProcess.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BasePrice")
                        .HasColumnType("float");

                    b.Property<double?>("OrderCS")
                        .HasColumnType("float");

                    b.Property<double?>("OrderPC")
                        .HasColumnType("float");

                    b.Property<string>("Packing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OrderProcess.Core.Entities.Products", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TaxRate")
                        .HasColumnType("float");

                    b.Property<double>("basePrice")
                        .HasColumnType("float");

                    b.Property<DateOnly>("basePriceEffDate")
                        .HasColumnType("date");

                    b.Property<int>("catcode")
                        .HasColumnType("int");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("pricewtax")
                        .HasColumnType("float");

                    b.Property<string>("proddesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prodno")
                        .HasColumnType("int");

                    b.Property<double>("unitcost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("RamProduct");
                });

            modelBuilder.Entity("OrderProcess.Core.Entities.Salesman", b =>
                {
                    b.Property<bool>("activecs")
                        .HasColumnType("bit");

                    b.Property<string>("area1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("area2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ckey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("csman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("custkey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dcode")
                        .HasColumnType("int");

                    b.Property<int>("desig")
                        .HasColumnType("int");

                    b.Property<string>("desigabb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("desigdesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("district")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dsignation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("empno")
                        .HasColumnType("int");

                    b.Property<int>("empvisor")
                        .HasColumnType("int");

                    b.Property<string>("fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("incid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plate_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salesman")
                        .HasColumnType("int");

                    b.Property<string>("smancode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("smanname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sono")
                        .HasColumnType("int");

                    b.Property<string>("statdesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supervisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("whseno")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("salesman", (string)null);
                });

            modelBuilder.Entity("OrderProcess.Core.Entities.categorygroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("groupdesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("groupno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoryGroups");
                });

            modelBuilder.Entity("OrderProcess.Core.Entities.OrderEntities", b =>
                {
                    b.HasOne("OrderProcess.Core.Entities.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderProcess.Core.Entities.Product", "Products")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("customer");
                });
#pragma warning restore 612, 618
        }
    }
}
